name: Auto Copy Issue Labels to All PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    paths:
      - '.github/workflows/auto-copy-labels.yml'
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  copy-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Process All PRs
      uses: actions/github-script@v6
      with:
        script: |
          const processPR = async (prNumber) => {
            console.log(`Processing PR #${prNumber}`);
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.name,
              pull_number: prNumber
            });
            
            const issueNumber = pr.body.match(/#(\d+)/)?.[1];
            if (!issueNumber) {
              console.log(`No issue number found in PR #${prNumber}`);
              return;
            }
            
            console.log(`Found issue #${issueNumber} for PR #${prNumber}`);
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: issueNumber
            });
            
            if (issue.labels.length > 0) {
              await github.rest.issues.addLabels({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.name,
                labels: issue.labels.map(label => label.name)
              });
              console.log(`Labels copied to PR #${prNumber}`);
            } else {
              console.log(`No labels to copy for PR #${prNumber}`);
            }
          };

          const { data: prs } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.name,
            state: 'open'
          });
          
          console.log(`Found ${prs.length} open PRs`);
          for (const pr of prs) {
            await processPR(pr.number);
          }
