name: Debug Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print debug information
        run: |
          echo "Workflow is running!"
          echo "Current time (UTC): $(date -u)"
          echo "GitHub context: ${{ toJson(github) }}"
