name: PR Issue Labeler

on:
  pull_request:
    types:
      - opened
      - edited
  workflow_dispatch:  # Trigger when this action is added for the first time
  schedule:           # Optional: run periodically to catch any missed PRs
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  label_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get PR information
      id: pr_info
      uses: actions-ecosystem/action-get-issue-number@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Check for Issue Number
      id: issue_check
      run: |
        ISSUE_NUMBER=$(echo "${{ steps.pr_info.outputs.issue_number }}" | grep -oP '#\d+')
        if [ -z "$ISSUE_NUMBER" ]; then
          echo "No issue number found"
          echo "::set-output name=issue_found::false"
        else
          echo "Issue number found: $ISSUE_NUMBER"
          echo "::set-output name=issue_found::true"
        fi

    - name: Comment if no issue number
      if: steps.issue_check.outputs.issue_found == 'false'
      run: |
        curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d '{"body":"Please add the issue number in the description. Example: `#123`"}' \
        "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

    - name: Add Labels from Issue
      if: steps.issue_check.outputs.issue_found == 'true'
      run: |
        ISSUE_NUMBER=$(echo "${{ steps.pr_info.outputs.issue_number }}" | grep -oP '\d+')
        ISSUE_LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels" | jq -r '.[].name')
        
        curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d "{\"labels\": [${ISSUE_LABELS}]}" \
        "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"
