name: Sync PR Labels with Linked Issue

on:
  pull_request:
    types: [opened, edited, synchronize]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        uses: cli/cli@v2

      - name: Get PR information
        id: pr_info
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          if [ -z "$PR_NUMBER" ]; then
            PR_NUMBER=$(gh pr list --limit 1000 --json number --jq '.[].number' | head -n 1)
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          
          PR_BODY=$(gh pr view $PR_NUMBER --json body --jq '.body')
          echo "PR_BODY<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Extract issue number and get labels
        id: issue_info
        run: |
          PR_BODY="${{ steps.pr_info.outputs.PR_BODY }}"
          ISSUE_NUMBER=$(echo "$PR_BODY" | grep -oP '(?<=\#)\d+' | head -n 1)
          
          if [ -n "$ISSUE_NUMBER" ]; then
            echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
            LABELS=$(gh issue view $ISSUE_NUMBER --json labels --jq '.labels[].name' | tr '\n' ',' | sed 's/,$//')
            echo "LABELS=$LABELS" >> $GITHUB_OUTPUT
          else
            echo "ISSUE_NUMBER=" >> $GITHUB_OUTPUT
            echo "LABELS=" >> $GITHUB_OUTPUT
          fi

      - name: Apply labels to PR
        if: steps.issue_info.outputs.LABELS != ''
        run: |
          PR_NUMBER=${{ steps.pr_info.outputs.PR_NUMBER }}
          LABELS="${{ steps.issue_info.outputs.LABELS }}"
          gh pr edit $PR_NUMBER --add-label "$LABELS"

      - name: Comment if no issue found
        if: steps.issue_info.outputs.ISSUE_NUMBER == ''
        run: |
          PR_NUMBER=${{ steps.pr_info.outputs.PR_NUMBER }}
          gh pr comment $PR_NUMBER --body "Please link an issue number in the description using the format #issue_number."

      - name: Notify if no labels on linked issue
        if: steps.issue_info.outputs.ISSUE_NUMBER != '' && steps.issue_info.outputs.LABELS == ''
        run: |
          echo "No labels found on the linked issue. No labels will be applied."

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
