name: Auto-label PR based on Issue

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  auto_label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm init -y
          npm install @actions/github @actions/core

      - name: Run PR Label Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/pr-labeler.js
